### ISSUE TITLE
Component List with Component Identification Numbers

### ISSUE THREAD

**Issue by BananaBonanza** [louvill/AAE535dPCalc#2]
### Category: Infrastructure

We want to construct a comprehensive component list with corresponding three letter identifier codes.  For example, a straight line pipe may be assigned a Component Identification (CID) as LNE. 

This does not have to be a python file. Excel, CSV, or even a text file will work for this. We just want a actual list that will eventually put into Python

**Comment by louvill** [comment]
LNE
VLV
ORF
INJ
BED

**Comment by louvill** [comment]
BND

**Comment by tshahin** [comment]
Maybe BED can be CAT instead to make it less confusing with BND

**Comment by tshahin** [comment]
SPL (Split)

**Comment by tshahin** [comment]
PT
TC
