### ISSUE TITLE
Build List of Required Parameters for Each Component

### ISSUE THREAD

**Issue by BananaBonanza** [louvill/AAE535dPCalc#3]
### Topic: Infrastructure

Since each component will require different inputs to calculate the pressure drop (bends requiring turning angle for example) it would be useful to have a full list of all inputs that each type of component needs in order to calculate the pressure drop across that component.

Extra brownie points for including ideas of how to parse "required parameters" for components like venturis.

**Comment by louvill** [comment]
LNE
Inside area
- If circle, it can be OD and wall thickness
- If other shape, would be easiest to have internal area directly

Mass flow rate
Hydraulic diameter
Fluid density
Fluid viscosity
Fluid temperature if being used for density and viscosity
Length
Height change

**Comment by louvill** [comment]
VLV
Flow coefficient
Specific gravity/density
N value (depends on units)

**Comment by louvill** [comment]
ORF
Discharge coefficient
Flow coefficient
Vapor pressure
Specific gravity/density
N value (depends on units)

**Comment by louvill** [comment]
INJ
This might be same as orifice, not sure its work having it on its own

**Comment by louvill** [comment]
BED
Upstream pressure
Pressure drop correlation (we can pick one as a default)
Load factor/mass flow rate and cross-sectional area

**Comment by louvill** [comment]
BND
Same as LNE but including the following
Bend radius
Bend angle
Whether it is flat or goes up/down

**Comment by louvill** [comment]
SPL
Inside area

- If circle, it can be OD and wall thickness
- If other shape, would be easiest to have internal area directly

Mass flow rate
Hydraulic diameter
Fluid density
Fluid viscosity
Fluid temperature if being used for density and viscosity
Length
Height change
Kt loss
