### ISSUE TITLE
UNITS! WE FORGOT ABOUT UNITS!

### ISSUE THREAD

**Issue by BananaBonanza** [louvill/AAE535dPCalc#30]
### Give a brief description of what the task will accomplish
The program doesn't currently have a unit system. I am assuming that this will all be in SI just because that will be the easiest to code, but we need to look at allowing for unit definitions by the user and then changing those units into ones we can work with.

### Describe the solution you'd like
We may need a whole new sub function (Possibly a decomposition of [A21](https://github.com/louvill/AAE535dPCalc/blob/master/bin/A21.py) ) that will allow the user to select what unit system they're using and then convert their entries into SI for the calculations.

We will then need ANOTHER subfunction (possibly a decomposition of [A32](https://github.com/louvill/AAE535dPCalc/blob/master/bin/A32.py)) that converts back to the original units the user requested.

### Describe alternatives you've considered
One alternative is to say fuck it and only use SI units for all of our calculations. We would need to alter [A21](https://github.com/louvill/AAE535dPCalc/blob/master/bin/A21.py) only slightly to give the user context into what units they have to plug into the program in order to get the results they want.

### Additional context
If anyone is actually reading this, thank you for looking at this documentation. I'm really trying to be as clear and as thorough as possible when I write these issues and I know it's a lot of text. So I appreciate you taking the time to read it.

**Comment by lugom-97** [comment]
I'd suggest doing only SI units. Conversions are fairly easy for the user to do on their own part, and when you use English units, there tends to be a lot of different 'conventions' used. For example, inside diameter of a pipe might be in inches, but may possibly be in feet for a longer pipe. Metric is easier, both for the math, and the code. It keeps things consistent.
